export const PAY_CASH_TABS = {
  DEPOSIT: 'Deposit',
  WITHDRAW: 'Withdraw',
  INVEST: 'Invest',
  CONVERTED: 'Converted'
}

export const CASH_PAGES = {
  PAY_CASH: 'PAY_CASH',
  TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',

  DEPOSIT_CURRENCY_CHOOSE: 'DEPOSIT_CURRENCY_CHOOSE',
  WITHDRAW_CURRENCY_CHOOSE: 'WITHDRAW_CURRENCY_CHOOSE',
  CONVERTED_FROM_CURRENCY_CHOOSE: 'CONVERTED_FROM_CURRENCY_CHOOSE',
  CONVERTED_TO_CURRENCY_CHOOSE: 'CONVERTED_TO_CURRENCY_CHOOSE',
  INVEST_CURRENCY_CHOOSE: 'INVEST_CURRENCY_CHOOSE',

  DEPOSIT_PAY_WAY_CHOOSE: 'DEPOSIT_PAY_WAY_CHOOSE',
  WITHDRAW_PAY_WAY_CHOOSE: 'WITHDRAW_PAY_WAY_CHOOSE'
}

export const INVEST_PAGES = {
  SEND: 'SEND',
  RECEIVE: 'RECEIVE'
}

export const PAYMENT_CODE = {
  DEPOSIT: 'deposit',
  WITHDRAW: 'withdraw'
}

export const TRANSACTION_HISTORY_PAGES = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW'
}

export const TRANSACTION_HISTORY_PAGINATION_SIZES = [
  10, 20, 30, 40, 50
]

export const PAYMENT_STATES = {
  CREATED: 'created',
  COMPLETED: 'completed',
  PROCESSING: 3,
  CANCELED: 4,
  REGISTERED: 5,
  REJECTED: 6,
  ERROR: 7
}
