export const modalsNames = {
  DAC: 'DAC',
  DEPOSIT_BONUS_LIST: 'DEPOSIT_BONUS_LIST',
  DEPOSIT_BONUS_INFO: 'DEPOSIT_BONUS_INFO',
  WHEEL_BONUS_LIST: 'WHEEL_BONUS_LIST',
  AFF_RULES_INFO: 'AFF_RULES_INFO',
  AFF_COMMIS_INFO: 'AFF_COMMIS_INFO'
}
